spring:
  h2:
    console:
      enabled: true
      path: /console
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: my_id
            client-secret: my_secret
          facebook:
            client-id: my_id
            client-secret: my_secret

  thymeleaf:
    prefix=classpath: templates/
    suffix: .html
    check-template-location: true
    cache: false
  mvc:
    static-path-pattern: "/static/**"
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/fourartist
    username: hong
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
          #show_sql: true
        format_sql: true
custom:
  oauth2:
    kakao:
      client-id: my_id
      client-secret: my_secret
    naver:
      client-id: my_id
      client-secret: my_secret
logging.level:
  org.hibernate.SQL: debug
  org.springframework.security: DEBUG
  org.springframework.web: DEBUG

server:
  ssl:
    key-store: 4rt-keystore.p12
    key-store-type: PKCS12
    key-store-password: tlsghdcjf41!
    key-alias: spring
  port: 8443
# org.hibernate.type: trace
